<?xml version="1.0" encoding="UTF-8"?>
<definitions name="myVentaLibros" targetNamespace="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/myVentaLibros"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/myVentaLibros" xmlns:ns="http://xml.netbeans.org/schema/ventaXmlSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/myVentaLibros">
            <xsd:import namespace="http://xml.netbeans.org/schema/ventaXmlSchema" schemaLocation="ventaXmlSchema.xsd"/>
        </xsd:schema>
    </types>
    <message name="myVentaLibrosOperationRequest">
        <part name="part1" element="ns:myInput"/>
    </message>
    <message name="myVentaLibrosOperationResponse">
        <part name="part1" element="ns:myOutput"/>
    </message>
    <message name="operationFault">
        <part name="part1" element="ns:myFault"/>
    </message>
    <portType name="myVentaLibrosPortType">
        <operation name="myVentaLibrosOperation">
            <input name="input1" message="tns:myVentaLibrosOperationRequest"/>
            <output name="output1" message="tns:myVentaLibrosOperationResponse"/>
            <fault name="fault1" message="tns:operationFault"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="myVentaLibros">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="myVentaLibrosPortTypeRole" portType="tns:myVentaLibrosPortType"/>
    </plnk:partnerLinkType>
</definitions>
