<?xml version="1.0" encoding="UTF-8"?>
<definitions name="VentaLibros" targetNamespace="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/VentaLibros"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/VentaLibros" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="VentaLibrosOperationRequest">
        <part name="ISBN" type="xsd:string"/>
        <part name="idCliente" type="xsd:int"/>
        <part name="unidades" type="xsd:int"/>
        <part name="precioUnidad" type="xsd:int"/>
        <part name="idCredito" type="xsd:int"/>
    </message>
    <message name="VentaLibrosOperationResponse">
        <part name="resultado" type="xsd:string"/>
    </message>
    <message name="VentaLibrosOperationFault">
        <part name="creditoNoValido" type="xsd:string"/>
        <part name="libroNoExiste" type="xsd:string"/>
        <part name="inventarioInsuficiente" type="xsd:string"/>
        <part name="CreditoInsuficiente" type="xsd:string"/>
        <part name="ClienteInvalido" type="xsd:string"/>
    </message>
    <portType name="VentaLibrosPortType">
        <operation name="VentaLibrosOperation">
            <input name="input1" message="tns:VentaLibrosOperationRequest"/>
            <output name="output1" message="tns:VentaLibrosOperationResponse"/>
            <fault name="fault1" message="tns:VentaLibrosOperationFault"/>
        </operation>
    </portType>
    <binding name="VentaLibrosBinding" type="tns:VentaLibrosPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="VentaLibrosOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/VentaLibros"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/VentaLibros"/>
            </output>
            <fault name="fault1">
                <soap:fault name="fault1" use="literal" namespace="http://j2ee.netbeans.org/wsdl/tienda_BPEL/DescriptorBPEL/VentaLibros"/>
            </fault>
        </operation>
    </binding>
    <service name="VentaLibrosService">
        <port name="VentaLibrosPort" binding="tns:VentaLibrosBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/VentaLibrosService/VentaLibrosPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="VentaLibros">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="VentaLibrosPortTypeRole" portType="tns:VentaLibrosPortType"/>
    </plnk:partnerLinkType>
</definitions>
