<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="wsPagosWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/wsPagosWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/wsPagosWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ws_pagos/">
    <import location="http://localhost:8080/WA_Almacen/wsPagos?WSDL" namespace="http://ws_pagos/"/>
    <plnk:partnerLinkType name="wsPagosLinkType">
        <plnk:role name="wsPagosRole" portType="ns:wsPagos"/>
    </plnk:partnerLinkType>
</definitions>
